# Read and validate data

This notebook is designed just for convenience

In [21]:
from pathlib import Path
import numpy as np
import pandas as pd
import xarray as xr

def find_repo_root() -> Path:
    for candidate in [Path.cwd(), *Path.cwd().parents]:
        if (candidate / "data").is_dir():
            return candidate
    raise FileNotFoundError("Could not find a repository containing data/")

def compute_scalar(value):
    value = value.compute() if hasattr(value, "compute") else value
    return value.item() if hasattr(value, "item") else value

def inspect_store(kind: str, path: Path) -> list[dict]:
    relative_path = path.relative_to(REPO_ROOT)
    print(f"\n{kind.upper()}: {relative_path}")
    opener = xr.open_zarr(path, consolidated=False) if kind == "zarr" else xr.open_dataset(path, decode_cf=True, mask_and_scale=True)
    with opener as ds:
        print("Dimensions:", dict(ds.sizes))
        print("Coordinates:", list(ds.coords))
        print("Data variables:", list(ds.data_vars))
        print("Global attributes:", dict(ds.attrs))
        print("Dataset encoding keys:", sorted(ds.encoding))
        rows = []
        for name, da in ds.variables.items():
            size = int(da.size)
            missing = int(compute_scalar(da.isnull().sum())) if size else 0
            row = {"store_type": kind, "path": str(relative_path), "name": name,
                   "role": "coordinate" if name in ds.coords else "data",
                   "dtype": str(da.dtype), "dims": tuple(da.dims), "shape": tuple(da.shape),
                   "size": size, "missing": missing,
                   "missing_pct": round(100 * missing / size, 3) if size else 0.0,
                   "attrs": dict(da.attrs)}
            if size and da.dtype.kind in "iufc":
                row["finite"] = int(compute_scalar(np.isfinite(da).sum()))
                if row["finite"]:
                    row["min"] = compute_scalar(da.min(skipna=True))
                    row["max"] = compute_scalar(da.max(skipna=True))
            rows.append(row)
            print(f"  {name}: missing={missing}/{size} ({row['missing_pct']}%), dtype={row['dtype']}, shape={row['shape']}")
        return rows

REPO_ROOT = find_repo_root()
DATA_ROOT = REPO_ROOT / "data"
raw_files = sorted((DATA_ROOT / "raw").rglob("*.nc"))
interim_files = sorted((DATA_ROOT / "interim").rglob("*.nc"))
zarr_stores = sorted(path for path in (DATA_ROOT / "zarr").iterdir()
                     if path.is_dir() and ((path / "zarr.json").exists() or (path / ".zgroup").exists()))
print(f"Found {len(raw_files)} raw, {len(interim_files)} interim, and {len(zarr_stores)} Zarr stores.")

Found 30 raw, 30 interim, and 1 Zarr stores.

## RAW data

In [17]:
print("=" * 100)
print(f"RAW DATA ({len(raw_files)} files)")
print("=" * 100)
raw_rows = []
for raw_path in raw_files:
    raw_rows.extend(inspect_store("raw", raw_path))
raw_variables = pd.DataFrame(raw_rows)
display(raw_variables.sort_values(["path", "role", "name"]))

====================================================================================================
RAW DATA (30 files)
====================================================================================================

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006010000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']
Global attributes: {'date_created': '2020-10-23T07:20:57Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-01T00:00:00Z', 'image_reference_time': '2020-06-01T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'institution': 'IM-PT', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': '2020-10-23T07:20:57Z - NetCDF reprojected product ; 2020-06-02T00:00:24Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006010000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'Conventions': 'CF-1.6', 'netcdf_version_id': 'netCDF4'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=7568883/10246401 (73.869%), dtype=float64, shape=(1, 3201, 3201)
  crs: missing=0/1 (0.0%), dtype=|S1, shape=()
  quality_flag: missing=2204174/10246401 (21.512%), dtype=float64, shape=(1, 3201, 3201)
  lat: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  lon: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006020000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']
Global attributes: {'date_created': '2020-10-23T07:21:42Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-02T00:00:00Z', 'image_reference_time': '2020-06-02T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'institution': 'IM-PT', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': '2020-10-23T07:21:42Z - NetCDF reprojected product ; 2020-06-03T00:00:22Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006020000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'Conventions': 'CF-1.6', 'netcdf_version_id': 'netCDF4'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=7567763/10246401 (73.858%), dtype=float64, shape=(1, 3201, 3201)
  crs: missing=0/1 (0.0%), dtype=|S1, shape=()
  quality_flag: missing=2204174/10246401 (21.512%), dtype=float64, shape=(1, 3201, 3201)
  lat: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  lon: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006030000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']
Global attributes: {'date_created': '2020-10-23T07:22:28Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-03T00:00:00Z', 'image_reference_time': '2020-06-03T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'institution': 'IM-PT', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': '2020-10-23T07:22:28Z - NetCDF reprojected product ; 2020-06-04T02:02:23Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006030000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'Conventions': 'CF-1.6', 'netcdf_version_id': 'netCDF4'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=7553006/10246401 (73.714%), dtype=float64, shape=(1, 3201, 3201)
  crs: missing=0/1 (0.0%), dtype=|S1, shape=()
  quality_flag: missing=2204174/10246401 (21.512%), dtype=float64, shape=(1, 3201, 3201)
  lat: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  lon: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006040000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']
Global attributes: {'date_created': '2020-10-23T07:23:13Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-04T00:00:00Z', 'image_reference_time': '2020-06-04T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'institution': 'IM-PT', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': '2020-10-23T07:23:13Z - NetCDF reprojected product ; 2020-06-05T00:00:23Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006040000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'Conventions': 'CF-1.6', 'netcdf_version_id': 'netCDF4'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=7558183/10246401 (73.764%), dtype=float64, shape=(1, 3201, 3201)
  crs: missing=0/1 (0.0%), dtype=|S1, shape=()
  quality_flag: missing=2204174/10246401 (21.512%), dtype=float64, shape=(1, 3201, 3201)
  lat: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  lon: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006050000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']
Global attributes: {'date_created': '2020-10-23T07:23:58Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-05T00:00:00Z', 'image_reference_time': '2020-06-05T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'institution': 'IM-PT', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': '2020-10-23T07:23:58Z - NetCDF reprojected product ; 2020-06-06T00:00:22Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006050000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'Conventions': 'CF-1.6', 'netcdf_version_id': 'netCDF4'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=7558393/10246401 (73.766%), dtype=float64, shape=(1, 3201, 3201)
  crs: missing=0/1 (0.0%), dtype=|S1, shape=()
  quality_flag: missing=2204174/10246401 (21.512%), dtype=float64, shape=(1, 3201, 3201)
  lat: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  lon: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006060000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']
Global attributes: {'date_created': '2020-10-23T07:24:44Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-06T00:00:00Z', 'image_reference_time': '2020-06-06T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'institution': 'IM-PT', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': '2020-10-23T07:24:44Z - NetCDF reprojected product ; 2020-06-07T00:00:23Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006060000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'Conventions': 'CF-1.6', 'netcdf_version_id': 'netCDF4'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=7558694/10246401 (73.769%), dtype=float64, shape=(1, 3201, 3201)
  crs: missing=0/1 (0.0%), dtype=|S1, shape=()
  quality_flag: missing=2204174/10246401 (21.512%), dtype=float64, shape=(1, 3201, 3201)
  lat: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  lon: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006070000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']
Global attributes: {'date_created': '2020-10-23T07:25:28Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-07T00:00:00Z', 'image_reference_time': '2020-06-07T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'institution': 'IM-PT', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': '2020-10-23T07:25:28Z - NetCDF reprojected product ; 2020-06-08T00:00:23Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006070000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'Conventions': 'CF-1.6', 'netcdf_version_id': 'netCDF4'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=7558675/10246401 (73.769%), dtype=float64, shape=(1, 3201, 3201)
  crs: missing=0/1 (0.0%), dtype=|S1, shape=()
  quality_flag: missing=2204174/10246401 (21.512%), dtype=float64, shape=(1, 3201, 3201)
  lat: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  lon: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006080000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']
Global attributes: {'date_created': '2020-10-23T07:26:13Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-08T00:00:00Z', 'image_reference_time': '2020-06-08T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'institution': 'IM-PT', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': '2020-10-23T07:26:13Z - NetCDF reprojected product ; 2020-06-09T00:00:23Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006080000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'Conventions': 'CF-1.6', 'netcdf_version_id': 'netCDF4'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=7559089/10246401 (73.773%), dtype=float64, shape=(1, 3201, 3201)
  crs: missing=0/1 (0.0%), dtype=|S1, shape=()
  quality_flag: missing=2204174/10246401 (21.512%), dtype=float64, shape=(1, 3201, 3201)
  lat: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  lon: missing=0/3201 (0.0%), dtype=float32, shape=(3201,)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)

RAW: data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006090000.nc
Dimensions: {'time': 1, 'lat': 3201, 'lon': 3201}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['METREF', 'crs', 'quality_flag']

,store_type,path,name,role,dtype,dims,shape,size,missing,missing_pct,attrs,finite,min,max
3,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,lat,coordinate,float32,"(lat,)","(3201,)",3201,0,0.000,"{'units': 'degrees_north', 'standard_name': 'l...",3201.0,-80.0,80.00
4,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,lon,coordinate,float32,"(lon,)","(3201,)",3201,0,0.000,"{'units': 'degrees_east', 'standard_name': 'lo...",3201.0,-80.0,80.00
5,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,time,coordinate,datetime64[ns],"(time,)","(1,)",1,0,0.000,"{'long_name': 'time', 'axis': 'T'}",NaN,NaN,NaN
0,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,METREF,data,float64,"(time, lat, lon)","(1, 3201, 3201)",10246401,7568883,73.869,"{'long_name': 'METREF', 'units': 'mm/day', 'gr...",2677518.0,0.0,6.59
1,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,crs,data,|S1,(),(),1,0,0.000,"{'grid_mapping_name': 'latitude_longitude', 'l...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,lon,coordinate,float32,"(lon,)","(3201,)",3201,0,0.000,"{'units': 'degrees_east', 'standard_name': 'lo...",3201.0,-80.0,80.00
179,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,time,coordinate,datetime64[ns],"(time,)","(1,)",1,0,0.000,"{'long_name': 'time', 'axis': 'T'}",NaN,NaN,NaN
174,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,METREF,data,float64,"(time, lat, lon)","(1, 3201, 3201)",10246401,7562111,73.803,"{'long_name': 'METREF', 'units': 'mm/day', 'gr...",2684290.0,0.0,6.69
175,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,crs,data,|S1,(),(),1,0,0.000,"{'grid_mapping_name': 'latitude_longitude', 'l...",NaN,NaN,NaN
176,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,quality_flag,data,float64,"(time, lat, lon)","(1, 3201, 3201)",10246401,2204174,21.512,"{'long_name': 'QFLAGS', 'grid_mapping': 'crs',...",8042227.0,-4.0,6.00

## INTERIM data

In [22]:
print("=" * 100)
print(f"INTERIM DATA ({len(interim_files)} files)")
print("=" * 100)
interim_rows = []
for interim_path in interim_files:
    interim_rows.extend(inspect_store("interim", interim_path))
interim_variables = pd.DataFrame(interim_rows)
display(interim_variables.sort_values(["path", "role", "name"]))

====================================================================================================
INTERIM DATA (30 files)
====================================================================================================

INTERIM: data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006010000_processed.nc
Dimensions: {'time': 1, 'lat': 91, 'lon': 121}
Coordinates: ['time', 'lon', 'lat']
Data variables: ['METREF', 'quality_flag']
Global attributes: {'CDI': 'Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)', 'Conventions': 'CF-1.6', 'institution': 'IM-PT', 'date_created': '2020-10-23T07:20:57Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-01T00:00:00Z', 'image_reference_time': '2020-06-01T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': 'Thu Oct 15 13:51:02 2026: cdo -L -f nc4 -O merge /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.vW0MLH.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.qa_remap.NgSKvs.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.merged.s04a2g.nc\nThu Oct 15 13:51:02 2026: cdo -L -f nc4 -O -remapbil,/mnt/c/Users/b1113715/Downloads/tutorial-repo/code/preprocess_utils/grid.txt /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.I3DNFE.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.vW0MLH.nc\nThu Oct 15 13:51:02 2026: cdo -L -f nc4 -O -delname,quality_flag /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.u3twOX.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.I3DNFE.nc\nThu Oct 15 13:51:01 2026: cdo -L -f nc4 -O -sellonlatbox,-17.475,-11.025,12.075,16.925 /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/raw/METREF/2020/06/NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006010000.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.u3twOX.nc\n2020-10-23T07:20:57Z - NetCDF reprojected product ; 2020-06-02T00:00:24Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006010000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'netcdf_version_id': 'netCDF4', 'CDO': 'Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=1039/11011 (9.436%), dtype=float32, shape=(1, 91, 121)
  quality_flag: missing=0/11011 (0.0%), dtype=float64, shape=(1, 91, 121)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)
  lon: missing=0/121 (0.0%), dtype=float64, shape=(121,)
  lat: missing=0/91 (0.0%), dtype=float64, shape=(91,)

INTERIM: data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006020000_processed.nc
Dimensions: {'time': 1, 'lat': 91, 'lon': 121}
Coordinates: ['time', 'lon', 'lat']
Data variables: ['METREF', 'quality_flag']
Global attributes: {'CDI': 'Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)', 'Conventions': 'CF-1.6', 'institution': 'IM-PT', 'date_created': '2020-10-23T07:21:42Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-02T00:00:00Z', 'image_reference_time': '2020-06-02T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': 'Thu Oct 15 13:51:02 2026: cdo -L -f nc4 -O merge /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.s6DEbH.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.qa_remap.JtgHHi.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.merged.GGKrpV.nc\nThu Oct 15 13:51:02 2026: cdo -L -f nc4 -O -remapbil,/mnt/c/Users/b1113715/Downloads/tutorial-repo/code/preprocess_utils/grid.txt /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.dETBnu.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.s6DEbH.nc\nThu Oct 15 13:51:02 2026: cdo -L -f nc4 -O -delname,quality_flag /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.UFxjNo.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.dETBnu.nc\nThu Oct 15 13:51:01 2026: cdo -L -f nc4 -O -sellonlatbox,-17.475,-11.025,12.075,16.925 /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/raw/METREF/2020/06/NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006020000.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.UFxjNo.nc\n2020-10-23T07:21:42Z - NetCDF reprojected product ; 2020-06-03T00:00:22Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006020000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'netcdf_version_id': 'netCDF4', 'CDO': 'Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=1039/11011 (9.436%), dtype=float32, shape=(1, 91, 121)
  quality_flag: missing=0/11011 (0.0%), dtype=float64, shape=(1, 91, 121)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)
  lon: missing=0/121 (0.0%), dtype=float64, shape=(121,)
  lat: missing=0/91 (0.0%), dtype=float64, shape=(91,)

INTERIM: data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006030000_processed.nc
Dimensions: {'time': 1, 'lat': 91, 'lon': 121}
Coordinates: ['time', 'lon', 'lat']
Data variables: ['METREF', 'quality_flag']
Global attributes: {'CDI': 'Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)', 'Conventions': 'CF-1.6', 'institution': 'IM-PT', 'date_created': '2020-10-23T07:22:28Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-03T00:00:00Z', 'image_reference_time': '2020-06-03T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': 'Thu Oct 15 13:51:02 2026: cdo -L -f nc4 -O merge /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.VIg6qM.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.qa_remap.mHdORL.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.merged.DxwYIR.nc\nThu Oct 15 13:51:02 2026: cdo -L -f nc4 -O -remapbil,/mnt/c/Users/b1113715/Downloads/tutorial-repo/code/preprocess_utils/grid.txt /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.LI4BKM.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.VIg6qM.nc\nThu Oct 15 13:51:02 2026: cdo -L -f nc4 -O -delname,quality_flag /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.Yg2huD.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.LI4BKM.nc\nThu Oct 15 13:51:01 2026: cdo -L -f nc4 -O -sellonlatbox,-17.475,-11.025,12.075,16.925 /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/raw/METREF/2020/06/NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006030000.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.Yg2huD.nc\n2020-10-23T07:22:28Z - NetCDF reprojected product ; 2020-06-04T02:02:23Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006030000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'netcdf_version_id': 'netCDF4', 'CDO': 'Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=1039/11011 (9.436%), dtype=float32, shape=(1, 91, 121)
  quality_flag: missing=0/11011 (0.0%), dtype=float64, shape=(1, 91, 121)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)
  lon: missing=0/121 (0.0%), dtype=float64, shape=(121,)
  lat: missing=0/91 (0.0%), dtype=float64, shape=(91,)

INTERIM: data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006040000_processed.nc
Dimensions: {'time': 1, 'lat': 91, 'lon': 121}
Coordinates: ['time', 'lon', 'lat']
Data variables: ['METREF', 'quality_flag']
Global attributes: {'CDI': 'Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)', 'Conventions': 'CF-1.6', 'institution': 'IM-PT', 'date_created': '2020-10-23T07:23:13Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-04T00:00:00Z', 'image_reference_time': '2020-06-04T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': 'Thu Oct 15 13:51:02 2026: cdo -L -f nc4 -O merge /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.hLfBYe.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.qa_remap.HkO7uH.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.merged.3R9XL4.nc\nThu Oct 15 13:51:02 2026: cdo -L -f nc4 -O -remapbil,/mnt/c/Users/b1113715/Downloads/tutorial-repo/code/preprocess_utils/grid.txt /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.pVNbt0.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.hLfBYe.nc\nThu Oct 15 13:51:02 2026: cdo -L -f nc4 -O -delname,quality_flag /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.Iq9oDA.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.pVNbt0.nc\nThu Oct 15 13:51:01 2026: cdo -L -f nc4 -O -sellonlatbox,-17.475,-11.025,12.075,16.925 /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/raw/METREF/2020/06/NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006040000.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.Iq9oDA.nc\n2020-10-23T07:23:13Z - NetCDF reprojected product ; 2020-06-05T00:00:23Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006040000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'netcdf_version_id': 'netCDF4', 'CDO': 'Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=1039/11011 (9.436%), dtype=float32, shape=(1, 91, 121)
  quality_flag: missing=0/11011 (0.0%), dtype=float64, shape=(1, 91, 121)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)
  lon: missing=0/121 (0.0%), dtype=float64, shape=(121,)
  lat: missing=0/91 (0.0%), dtype=float64, shape=(91,)

INTERIM: data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006050000_processed.nc
Dimensions: {'time': 1, 'lat': 91, 'lon': 121}
Coordinates: ['time', 'lon', 'lat']
Data variables: ['METREF', 'quality_flag']
Global attributes: {'CDI': 'Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)', 'Conventions': 'CF-1.6', 'institution': 'IM-PT', 'date_created': '2020-10-23T07:23:58Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-05T00:00:00Z', 'image_reference_time': '2020-06-05T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': 'Thu Oct 15 13:51:03 2026: cdo -L -f nc4 -O merge /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.qJpAZQ.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.qa_remap.A7R77d.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.merged.bl9Nth.nc\nThu Oct 15 13:51:03 2026: cdo -L -f nc4 -O -remapbil,/mnt/c/Users/b1113715/Downloads/tutorial-repo/code/preprocess_utils/grid.txt /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.aNYfzZ.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main_remap.qJpAZQ.nc\nThu Oct 15 13:51:03 2026: cdo -L -f nc4 -O -delname,quality_flag /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.o6Y6K7.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.main.aNYfzZ.nc\nThu Oct 15 13:51:03 2026: cdo -L -f nc4 -O -sellonlatbox,-17.475,-11.025,12.075,16.925 /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/raw/METREF/2020/06/NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006050000.nc /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/.clip.o6Y6K7.nc\n2020-10-23T07:23:58Z - NetCDF reprojected product ; 2020-06-06T00:00:22Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006050000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': np.float64(80.0), 'southernmost_latitude': np.float64(-80.0), 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. García-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meliá, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': np.float64(-80.0), 'westernmost_longitude': np.float64(80.0), 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'netcdf_version_id': 'netCDF4', 'CDO': 'Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)'}
Dataset encoding keys: ['source', 'unlimited_dims']
  METREF: missing=1039/11011 (9.436%), dtype=float32, shape=(1, 91, 121)
  quality_flag: missing=0/11011 (0.0%), dtype=float64, shape=(1, 91, 121)
  time: missing=0/1 (0.0%), dtype=datetime64[ns], shape=(1,)
  lon: missing=0/121 (0.0%), dtype=float64, shape=(121,)
  lat: missing=0/91 (0.0%), dtype=float64, shape=(91,)

INTERIM: data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006060000_processed.nc
Dimensions: {'time': 1, 'lat': 91, 'lon': 121}
Coordinates: ['time', 'lon', 'lat']
Data variables: ['METREF', 'quality_flag']

,store_type,path,name,role,dtype,dims,shape,size,missing,missing_pct,attrs,finite,min,max
4,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,lat,coordinate,float64,"(lat,)","(91,)",91,0,0.000,"{'standard_name': 'latitude', 'long_name': 'la...",91.0,12.250000,16.750000
3,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,lon,coordinate,float64,"(lon,)","(121,)",121,0,0.000,"{'standard_name': 'longitude', 'long_name': 'l...",121.0,-17.250000,-11.250000
2,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,time,coordinate,datetime64[ns],"(time,)","(1,)",1,0,0.000,"{'standard_name': 'time', 'long_name': 'time',...",NaN,NaN,NaN
0,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,METREF,data,float32,"(time, lat, lon)","(1, 91, 121)",11011,1039,9.436,"{'long_name': 'METREF', 'units': 'mm/day'}",9972.0,1.990010,5.629999
1,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,quality_flag,data,float64,"(time, lat, lon)","(1, 91, 121)",11011,0,0.000,{'long_name': 'QFLAGS'},11011.0,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,lat,coordinate,float64,"(lat,)","(91,)",91,0,0.000,"{'standard_name': 'latitude', 'long_name': 'la...",91.0,12.250000,16.750000
148,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,lon,coordinate,float64,"(lon,)","(121,)",121,0,0.000,"{'standard_name': 'longitude', 'long_name': 'l...",121.0,-17.250000,-11.250000
147,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,time,coordinate,datetime64[ns],"(time,)","(1,)",1,0,0.000,"{'standard_name': 'time', 'long_name': 'time',...",NaN,NaN,NaN
145,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,METREF,data,float32,"(time, lat, lon)","(1, 91, 121)",11011,1039,9.436,"{'long_name': 'METREF', 'units': 'mm/day'}",9972.0,1.640006,5.619974
146,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,quality_flag,data,float64,"(time, lat, lon)","(1, 91, 121)",11011,0,0.000,{'long_name': 'QFLAGS'},11011.0,0.000000,1.000000

## ZARR data

In [19]:
print("=" * 100)
print(f"ZARR DATA ({len(zarr_stores)} stores)")
print("=" * 100)
zarr_rows = []
for zarr_path in zarr_stores:
    zarr_rows.extend(inspect_store("zarr", zarr_path))
zarr_variables = pd.DataFrame(zarr_rows)
display(zarr_variables.sort_values(["path", "role", "name"]))

====================================================================================================
ZARR DATA (1 stores)
====================================================================================================

ZARR: data\zarr\metref_sample_1month.zarr
Dimensions: {'time': 30, 'lat': 552, 'lon': 576}
Coordinates: ['lat', 'lon', 'time']
Data variables: ['quality_flag', 'METREF']
Global attributes: {'CDI': 'Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)', 'Conventions': 'CF-1.6', 'institution': 'IM-PT', 'date_created': '2020-10-23T07:20:57Z', 'algorithm_version': '1.3.2', 'base_algorithm_version': '1.0.3', 'processing_level': '03', 'platform': 'MSG4', 'sensor': 'SEVI', 'parent_product_name': 'METREF;QFLAGS;-;-', 'time_coverage_start': '2020-06-01T00:00:00Z', 'image_reference_time': '2020-06-01T00:00:00Z', 'name': 'METREF', 'region_name': 'MSG-Disk', 'archive_facility': 'IPMA', 'license': 'Data is freely available for users registered at the LSA SAF website - lsa-saf.eumetsat.int', 'history': 'Wed Oct 14 10:45:01 2026: cdo -L -f nc4 -O -remapbil,/mnt/c/Users/b1113715/Downloads/tutorial-repo/code/preprocess_utils/grid.txt /tmp/tmp.nhKZV1CDqC /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/interim/2020/06/NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006010000_processed.nc.part\nWed Oct 14 10:45:01 2026: cdo -L -f nc4 -O -sellonlatbox,-17.3807,11.8253,-11.1441,16.852 /mnt/c/Users/b1113715/Downloads/tutorial-repo/data/raw/METREF/2020/06/NETCDF4_LSASAF_MSG_METREF_MSG-Disk_202006010000.nc /tmp/tmp.nhKZV1CDqC\n2020-10-23T07:20:57Z - NetCDF reprojected product ; 2020-06-02T00:00:24Z Original product file created: HDF5_LSASAF_MSG_METREF_MSG-Disk_202006010000', 'geospatial_lat_resolution': ' 0.05', 'geospatial_lon_resolution': ' 0.05', 'northernmost_latitude': 80.0, 'southernmost_latitude': -80.0, 'references': 'Data provided by the EUMETSAT Satellite Application Facility on Land Surface Analysis (LSA SAF; Trigo et al., 2011) http://lsa-saf.eumetsat.int Trigo, I. F., C. C. DaCamara, P. Viterbo, J.-L. Roujean, F. Olesen, C. Barroso, F. Camacho-de Coca, D. Carrer, S. C. Freitas, J. Garc\udcc3\udcada-Haro, B. Geiger, F. Gellens-Meulenberghs, N. Ghilain, J. Meli\udcc3\udca1, L. Pessanha, N. Siljamo, and A. Arboleda, 2011: The Satellite Application Facility on Land Surface Analysis. Int. J. Remote Sens., 32, 2725-2744, doi: 10.1080/01431161003743199', 'easternmost_longitude': -80.0, 'westernmost_longitude': 80.0, 'spatial_resolution': ' 0.05x 0.05', 'geospatial_lat_units': 'degrees_north', 'geospatial_lon_units': 'degrees_east', 'netcdf_version_id': 'netCDF4', 'CDO': 'Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)'}
Dataset encoding keys: ['source']
  quality_flag: missing=369/9538560 (0.004%), dtype=float64, shape=(30, 552, 576)
  METREF: missing=5756325/9538560 (60.348%), dtype=float32, shape=(30, 552, 576)
  lat: missing=0/552 (0.0%), dtype=float64, shape=(552,)
  lon: missing=0/576 (0.0%), dtype=float64, shape=(576,)
  time: missing=0/30 (0.0%), dtype=datetime64[ns], shape=(30,)

,store_type,path,name,role,dtype,dims,shape,size,missing,missing_pct,attrs,finite,min,max
2,zarr,data\zarr\metref_sample_1month.zarr,lat,coordinate,float64,"(lat,)","(552,)",552,0,0.000,"{'standard_name': 'latitude', 'long_name': 'la...",552.0,-10.944114,16.605886
3,zarr,data\zarr\metref_sample_1month.zarr,lon,coordinate,float64,"(lon,)","(576,)",576,0,0.000,"{'standard_name': 'longitude', 'long_name': 'l...",576.0,-17.180733,11.569267
4,zarr,data\zarr\metref_sample_1month.zarr,time,coordinate,datetime64[ns],"(time,)","(30,)",30,0,0.000,"{'standard_name': 'time', 'long_name': 'time',...",NaN,NaN,NaN
1,zarr,data\zarr\metref_sample_1month.zarr,METREF,data,float32,"(time, lat, lon)","(30, 552, 576)",9538560,5756325,60.348,"{'long_name': 'METREF', 'units': 'mm/day'}",3782235.0,0.710000,6.086871
0,zarr,data\zarr\metref_sample_1month.zarr,quality_flag,data,float64,"(time, lat, lon)","(30, 552, 576)",9538560,369,0.004,{'long_name': 'QFLAGS'},9538191.0,-4.000000,2.000000

## Missing-value comparison

In [20]:
all_variables = pd.concat([raw_variables, interim_variables, zarr_variables], ignore_index=True)
display(all_variables.loc[all_variables["missing"] > 0,
                          ["store_type", "path", "name", "role", "missing", "size", "missing_pct"]]
        .sort_values(["store_type", "missing_pct"], ascending=[True, False]))

,store_type,path,name,role,missing,size,missing_pct
265,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,METREF,data,194821,317952,61.274
180,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,METREF,data,191776,317952,60.316
185,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,METREF,data,191776,317952,60.316
190,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,METREF,data,191776,317952,60.316
195,interim,data\interim\2020\06\NETCDF4_LSASAF_MSG_METREF...,METREF,data,191776,317952,60.316
...,...,...,...,...,...,...,...
164,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,quality_flag,data,2204174,10246401,21.512
170,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,quality_flag,data,2204174,10246401,21.512
176,raw,data\raw\METREF\2020\06\NETCDF4_LSASAF_MSG_MET...,quality_flag,data,2204174,10246401,21.512
331,zarr,data\zarr\metref_sample_1month.zarr,METREF,data,5756325,9538560,60.348
330,zarr,data\zarr\metref_sample_1month.zarr,quality_flag,data,369,9538560,0.004